apiVersion: v1
kind: ConfigMap
metadata:
  name: pruner-config
  namespace: docker-registry
  labels:
    app: docker-registry-pruner
    tier: backend
data:
  registry-config.yml: |
    registry: http://docker-registry:5000
    username: {{ .Values.registry.username }}
    password: {{ .Values.registry.password }}
    parallel_workers: 10
    rules:
      - repos:
        - app/calculator
        keep_recent: 10
      - repos:
        - app/jmeter
        keep_recent: 5
