kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redisdata
  namespace: docker-registry
  labels:
    app: redis
    tier: backend
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi 
