apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-pv
  namespace: docker-registry
  labels:
    app: registry
    tier: backend
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.registry.storage }}
