apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
  namespace: docker-registry
  labels:
    app: registry
    tier: backend
type: Opaque
data:
  HTPASSWD: {{ .Values.registry.htpasswd }}
