apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-registry
  namespace: docker-registry
  labels:
    app: registry
    tier: frontend
data:
  registry-config.yml: |
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: redis
      filesystem:
        rootdirectory: /var/lib/registry
      delete:
        enabled: true
    redis:
      addr: redis-master:6379
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    auth:
      htpasswd:
        realm: basic-realm
        path: /auth/htpasswd
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
