apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  namespace: docker-registry
  labels:
    app: registry
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
        - name: docker-registry
          image: registry:2.6.2
          imagePullPolicy: IfNotPresent
          ports:
          - name: http
            containerPort: 5000
          volumeMounts:
          - name: config
            mountPath: /etc/docker/registry
            readOnly: true
          - name: htpasswd
            mountPath: /auth
            readOnly: true
          - name: docker-registry-persistent-storage
            mountPath: /var/lib/registry
          - name: cronfile
            mountPath: /etc/crontabs/
      volumes:
        - name: config
          configMap:
            name: docker-registry
            items:
              - key: registry-config.yml
                path: config.yml
        - name: htpasswd
          secret:
            secretName: docker-registry
            items:
            - key: HTPASSWD
              path: htpasswd
        - name: docker-registry-persistent-storage
          persistentVolumeClaim:
            claimName: docker-registry-pv
        - name: cronfile
          configMap:
            name: cronfile
